### ISSUE TITLE
Provider for Microsoft.Data.SQLite

### ISSUE THREAD

**Issue by hsorbo** [rspeele/Rezoom.SQL#19]
`Microsoft.Data.SQLite` currently supports many platforms while `System.Data.SQLite` is windows-only. By supporting M.D.S we will have sqlite support on macos etc. `Microsoft.Data.SQLite` is also netstandard2 compatible (as opposed to S.D.S) for when https://github.com/rspeele/Rezoom.SQL/issues/15 is getting addressed

**Comment by rspeele** [comment]
This probably already works if using an appropriate connection string and DbProviderFactory setup in [app.config](https://rspeele.gitbooks.io/rezoom-sql/doc/Configuration/AppConfig.html). Nothing at compile-time relies on System.Data.SQLite specifically being used at runtime.

There is one place where I'll want to add detection of that connection type, but it happens to already work since the default for unrecognized connection types is the same as for SQLite connections. That is the max # of parameters per SQL command, which is 999 for SQLite.
