### ISSUE TITLE
No such object : SQ011

### ISSUE THREAD

**Issue by jps** [rspeele/Rezoom.SQL#21]
Trying to get this working with an existing SQL Server DB

Code is as follows

```
namespace JPS.Core
module DataAccess =
    open FSharp.Data.Sql
    open Rezoom
    open Rezoom.SQL
    open Rezoom.SQL.Synchronous

    type Log = SQL<"""
        SELECT * from Logs
        """>

    let test =
        use connection = new ConnectionContext()        
        ()
```

Only thing is I'm getting the following error no matter what I try. I can connect to the DB with my connection string though SQL Server MMS and can query tables.  Also tried using FSharp.Data.Sql which appears to work fine... Error is 

> >C:\**********\**********\DataAccess.fs(8,16): error FS3033: The type provider 'Rezoom.SQL.Provider.Provider' reported an error: SQ011: No such object: ``Logs``.Log(2,23):        SELECT * from  ⇨ [Logs] ⇦

Any Idea what I'm doing wrong or how I can get more information out to debug?

**Comment by rspeele** [comment]
Hi,

Based on your statement about being able to connect to your database, I think you may be misunderstanding how this library works. With Rezoom.SQL the type provider **does not connect to any database**. In order to validate queries at compile time, it needs its own model of your schema, which it gets from reading migration scripts in your F# project. If you skim through [the tutorial](https://rspeele.gitbooks.io/rezoom-sql/doc/Tutorial/) you'll very quickly see an example initial migration, V1.model.sql.

This is intended to work well for green field projects where the database is created by the application, to serve the application's needs. Typically there, the first thing you'd write would be the `CREATE TABLE` statements for the model you've designed in your head, then you'd start writing F# code against that model, possibly tweaking it as you go. After a while you'd run the initial migration and test your code live, then as you continue to develop you would add [more migrations](https://rspeele.gitbooks.io/rezoom-sql/doc/Tutorial/AddingMigrations.html) to create more tables or [alter](https://rspeele.gitbooks.io/rezoom-sql/doc/Language/AlterTableStmt.html) the ones you already have.

It isn't as good a fit for applications where the database already exists and its schema is controlled by a DBA or by migrations written as part of another app. **In this respect Rezoom.SQL is the opposite of all the other F# database type providers.** [FSharp.Data.SqlClient](http://fsprojects.github.io/FSharp.Data.SqlClient/) might be a better match for your needs.

If you want to use Rezoom.SQL with an existing database, you can do it, but you still need a migration script from which the typechecker can understand your database schema, *even though this migration script never gets run*.

In your case you could add a file to your project called `V1.model.sql` and put `CREATE TABLE` statements in that file to inform the typechecker of your schema. I don't know what your `Logs` table has, but an example would be:

```sql
create table Logs ( Timestamp datetime, Message string(128) );
```

Then for all your `type Whatever = SQL<"...">` queries, the typechecker would know that there is a table called `Logs` that has those two columns.

It might be kind of a pain to write a fake CREATE statement for all your tables (well, all the tables that you care to write queries against), but that's what you'd have to do. There is an idea in #3 to have a console app that would auto-generate a migration like this from an existing database, but no progress on it so far.

**Comment by jps** [comment]
Thanks for taking the time to write such a detailed reply.  Especially after I rushed in and tried to use cool new shiny thing without spending enough time reading the manual...

I can see both advantages and disadvantages to having the SQL migrations file located in the project. Need to have a play and work out what's going to best for my needs.
