### ISSUE TITLE
Bug: Batching results over large queries

### ISSUE THREAD

**Issue by Risord** [rspeele/Rezoom.SQL#31]
Batching large queries with TSQL will fail to `SqlException: The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.`

Bug can be replicated by using hello world model provided by Rezoom.SQL.Provider & Rezoom.SQL.Provider.TSQL. Issue has been replicated to large number of different queries. Sample:
```
open Rezoom
open Rezoom.SQL
open Rezoom.SQL.Plans
open Rezoom.SQL.Migrations
open Rezoom.Execution
open Rezoom.PlanBuilder

type MyModel = SQLModel<".">

type InsertUser = SQL<"""
    insert into Users(Name, Email) values (@name, @email);
""">

[<EntryPoint>]
let main _ =
    MyModel.Migrate MigrationConfig.Default
    let data = List.init 2000 (fun i -> i.ToString() + "@test.com", None)
    let task =
        plan {
            for (email, name) in batch data do
                do! InsertUser.Command(email, name).Plan()
        }
        |> execute ExecutionConfig.Default
    task.Wait()
    0
```
This bug was noticed in issue #26 but since it was orginally asked as how-to question I will closed that and opened more clear bug report. As workaround batching and non-batching operations can be manually be used.

Btw library feels pretty stable now in general and we are currently using that for couple of real projects. How about nuget bump after this?

**Comment by rspeele** [comment]
Done & done. Nuget packages are now 0.7.0.

Turns out all that was necessary was to [reduce the hardcoded parameter limit for SQL server to be 2098](https://github.com/rspeele/Rezoom.SQL/commit/93835cc4d4e018bea085bc6c6a07b6ba4db7895d).

Apparently the SqlCommand implementation [uses two parameters for itself](https://stackoverflow.com/questions/8050091/sqlcommand-maximum-parameters-exception-at-2099-parameters).

**Comment by Risord** [comment]
Seems to work perfectly so far. Thanks!
