### ISSUE TITLE
Can you call stored procedures? 

### ISSUE THREAD

**Issue by erlis** [rspeele/Rezoom.SQL#35]
Hi, 

I've been researching Rezoom because I want to access some SQL Server stored procedures but I'm not able to find anything on the documentation for it. Is it supported? 

Thanks! 
Erlis

**Comment by rspeele** [comment]
Hi,

You can use a [vendor statement](https://rspeele.gitbooks.io/rezoom-sql/doc/Language/VendorStatements.html) to call stored procs. Since this bypasses the typechecker, and requires you to manually write an `imagine` clause if you want to read data coming from the sproc, rzsql's probably not a good fit if your project is mostly stored procedures. On the other hand if you're doing 95% plain queries and only need to run a stored procedure occasionally, the cost/benefit probably works out and it's worth the hassle.

Regards,
Robert
